Repository GTBitsOfGood/npp, pull requests merged in 2021-02, with the labels that each got.

#104 102-Enable logging out. Added some metrics to investigate what is cau…
  .env.local.example
  server/auth/BitsAuth0Provider.ts
  server/routes/NppApiRequest.ts
  server/routes/RouteFactory.ts
  server/utils/Authentication.ts
  server/utils/MetricReporter.ts
  src/pages/api/application.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/user.ts
  src/screens/App/Project/index.tsx
  utils/auth-utils.ts
Labels: Backend, bug

#107 Switch to JWT
  server/auth/UserTypeORM.ts
  server/models/User.ts
  server/models/index.ts
  server/mongodb/UserDocument.ts
  server/mongodb/actions/UserManager.ts
  src/actions/UserActions.ts
  src/components/Header/UserIcon/index.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/user.ts
Labels: Backend

#105 Report a problem frontend functionality
  package-lock.json
  package.json
  server/utils/ImageUpload.ts
  src/components/ImageUpload/ImageUpload.module.scss
  src/components/ImageUpload/index.tsx
  src/screens/App/ReportForm/index.tsx
  src/screens/App/ReportLanding/index.tsx
Labels: Frontend, enhancement

#114 Fixes Pagination & Implements Pre-Verification Screen
  src/actions/UserActions.ts
  src/pages/index.tsx
  src/screens/App/Project/index.tsx
  src/styles/App.scss
  utils/auth-utils.ts
Labels: enhancement, frontend, good first issue
